export const reviews = [
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAdcvfgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeob3424dSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5skdln2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdeorjhv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAsnkfjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdksmEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIy5ZAshdksmEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5ZAshdksmEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Pasta',
    itemID: 'ZQbIy5ZANwH2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'purchase',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Bread',
    itemID: 'ZQbIy5ZAshdjgSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  },
  {
    itemName: 'Fries',
    itemID: 'ZQbIyeobfwHfdSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '80',
    price: '105',
    viewTime: '25'
  },
  {
    itemName: 'Cheese',
    itemID: 'ZQbIy5Zdlbn2gSEcbdWl',
    categoryID: 'ddZdEdoTthv4PHpmMfB3',
    parentMenuID: '4flCYyqA43RiUqKqoRxK',
    restaurantID: 'ISZMcHTk3lRTI6JFpFg7vmogkk73',
    type: 'view',
    cost: '20',
    price: '55',
    viewTime: '45'
  }
]
