export const customerData = [
  {
    fname: "Jos",
    lname: "Buttle",
    age: 32,
    gender: "male",
    email: "jos@gmail.com",
  },
  {
    fname: "Shawn",
    lname: "Tait",
    age: 22,
    gender: "male",
    email: "tail@gmail.com",
  },
  {
    fname: "Sara",
    lname: "khan",
    age: 18,
    gender: "female",
    email: "sara@gmail.com",
  },
  {
    fname: "Ahmad",
    lname: "shehzad",
    age: 30,
    gender: "male",
    email: "ahmad@gmail.com",
  },
  {
    fname: "Shahid",
    lname: "khan",
    age: 40,
    gender: "male",
    email: "shahid@gmail.com",
  },
  {
    fname: "John",
    lname: "doe",
    age: 44,
    gender: "male",
    email: "doe@gmail.com",
  },
  {
    fname: "Sara",
    lname: "khan",
    age: 18,
    gender: "female",
    email: "sara@gmail.com",
  },
  {
    fname: "Ahmad",
    lname: "shehzad",
    age: 30,
    gender: "male",
    email: "ahmad@gmail.com",
  },
  {
    fname: "Shahid",
    lname: "khan",
    age: 40,
    gender: "male",
    email: "shahid@gmail.com",
  },
  {
    fname: "John",
    lname: "doe",
    age: 44,
    gender: "male",
    email: "doe@gmail.com",
  },
];
