export const orders = [
  {
    id: 1,
    name: "John Doe",
    itemsOrdered: "x2",
    price: "20 $",
    orderStatus: "pending",
    dishOrdered: "Pizza",
    qrCode: "1999",
    comments:
      "It’s a great experience. The ambiance is very welcoming and charming.",
  },
  {
    id: 2,
    name: "Munro",
    itemsOrdered: "x3",
    price: "10 $",
    orderStatus: "process",
    dishOrdered: "Pizza",
    qrCode: "2999",
    comments:
      "This place is great! Atmosphere is chill and cool but the staff is also really friendly.",
  },
  {
    id: 3,
    name: "Cena",
    itemsOrdered: "x2",
    price: "20 $",
    orderStatus: "ready",
    dishOrdered: "Pizza",
    qrCode: "2000",
    comments:
      "The food is absolutely amazing – everything we tasted melted in other mouths.",
  },
  {
    id: 4,
    name: "John Rambo",
    itemsOrdered: "x1",
    price: "20 $",
    orderStatus: "pending",
    dishOrdered: "Pizza",
    qrCode: "2000",
    comments: "I have to say, I enjoyed every single bite of the meal",
  },
  {
    id: 5,
    name: "John Doe",
    itemsOrdered: "x2",
    price: "20 $",
    orderStatus: "process",
    dishOrdered: "Pizza",
    qrCode: "3999",
    comments:
      "Excellent food. Menu is extensive and seasonal to a particularly high standard.",
  },
  {
    id: 6,
    name: "John Doe",
    itemsOrdered: "x2",
    price: "20 $",
    orderStatus: "pending",
    dishOrdered: "Pizza",
    qrCode: "1000",
    comments: "A restaurant with great service, food, and overall experience.",
  },
  {
    id: 7,
    name: "Munro",
    itemsOrdered: "x3",
    price: "10 $",
    orderStatus: "process",
    qrCode: "2999",
    comments:
      "Delicious food, waiters are very attentive, and super nice atmosphere",
    dishOrdered: "Russian",
  },
  {
    id: 8,
    name: "Cena",
    itemsOrdered: "x2",
    qrCode: "1999",
    comments: "Excellent, unassuming and wonderful find",
    price: "20 $",
    orderStatus: "ready",
    dishOrdered: "Italian pizza",
  },
  {
    id: 9,
    name: "John Rambo",
    itemsOrdered: "x1",
    qrCode: "2000",
    comments: "Top notch food, atmosphere, and wait staff.",
    price: "20 $",
    orderStatus: "pending",
    dishOrdered: "Pizza",
  },
  {
    id: 10,
    name: "John Doe",
    itemsOrdered: "x2",
    price: "20 $",
    orderStatus: "process",
    dishOrdered: "Pizza",
    qrCode: "1000",
    comments: "Stopped in for dinner and had a great meal.",
  },
];
